# Generated by Django 2.0.4 on 2018-05-18 00:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('pub_date', models.DateTimeField()),
                ('point_value', models.IntegerField(default=50)),
                ('current_amount_done', models.IntegerField(default=0)),
                ('amount_goal', models.IntegerField(default=1)),
                ('amount_per_increment', models.IntegerField(default=1)),
                ('times_completed', models.IntegerField(default=0)),
                ('units', models.CharField(max_length=50)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
