# Generated by Django 2.0.4 on 2018-05-20 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='times_completed',
        ),
    ]
